addons:
  postgresql: "9.4"
language: ruby
rvm:
 - "2.2.3"
script:
  - bundle exec rspec spec
  - bundle exec rake db:schema:load
  - bundle exec rake db:seed
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database tmta_test;' -U postgres