default: &default
  adapter: postgresql
  encoding: utf8
  username: developer
  password: 123
  template: template0
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tmta_dev

test:
  <<: *default
  database: tmta_test

production:
  adapter: postgresql
  encoding: utf8
  database: tmta_prod
  username: root
  password: 123
  template: template0 # Required for UTF8 encoding
